name: AdvancedBanther
version: 1.0
main: com.sunpowder.banther.advancedbanther
api-version: 1.16
commands:
  doomaxe:
    description: Summons the legendary DoomAxe
    usage: /doomaxe
    permission: advancedbanther.use
  doomaxe-admin:
    description: Manage DoomAxe permissions
    usage: /doomaxe-admin <add|remove|list> <player>
    permission: advancedbanther.admin
permissions:
  advancedbanther.use:
    description: Allows use of the DoomAxe command
    default: false
  advancedbanther.bypass:
    description: Bypasses all DoomAxe restrictions
    default: op
  advancedbanther.admin:
    description: Allows management of DoomAxe permissions
    default: op
